name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting: Cześć! Witamy na pokładzie statku pełnym radości!
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Problemy na morzu, kapitanie"
        pr-message: "Dzięki!"
